drivers: mediatek: Fix unused but set warning on typec driver
../../../../../../kernel/motorola/mt6853/drivers/misc/mediatek/typec/tcpc/pd_dpm_alt_mode_dp.c:352:6: error: variable 'local_index' set but not used [-Werror,-Wunused-but-set-variable]
        int local_index = -1, remote_index = -1;
            ^
1 error generated.